# observability/base.py
from abc import ABC, abstractmethod


class Observer(ABC):
    # ========== testcase ==========
    def testcase_start(self, name: str): ...
    def testcase_end(self, name: str): ...
    def testcase_fail(self, name: str, err: Exception): ...

    # ========== step ==========
    def step_start(self, name: str): ...
    def step_end(self, name: str, success: bool, duration: float): ...

    # ========== hook ==========
    def hook_start(self, phase: str, cmd: str): ...
    def hook_end(self, phase: str, cmd: str): ...
