[package]
name = "aitest-exf-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "exf-server"
path = "src/main.rs"

[dependencies]
aitest-core = { workspace = true }
aitest-scheduler = { workspace = true }
aitest-worker = { workspace = true }
aitest-broker = { workspace = true }
tokio = { workspace = true }
tokio-util = "0.7"
async-trait = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { workspace = true }
serde_json = { workspace = true }
